#!/usr/bin/env bash
#
# generate-contract-models.sh
# 使用 OpenAPI Generator 7.22.0 生成 Kotlin DTO
#
# 用法:
#   ./generate-contract-models.sh --output-dir <absolute-path>
#
# 要求:
#   - Java 21+
#   - 网络访问 (首次下载 CLI)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PROJECT_ROOT="$(cd "$APP_DIR/.." && pwd)"

# OpenAPI Generator CLI 版本和 SHA-256
OPENAPI_GENERATOR_VERSION="7.22.0"
OPENAPI_GENERATOR_SHA256="3f1e6ce5c6ad4f15242c6170ab43aad4bad771622617eeece4a7d4f72ffaf329"
OPENAPI_GENERATOR_JAR="openapi-generator-cli-${OPENAPI_GENERATOR_VERSION}.jar"
TOOLS_DIR="$APP_DIR/build/contract-tools"

# 解析参数
OUTPUT_DIR=""
while [[ $# -gt 0 ]]; do
  case $1 in
    --output-dir)
      OUTPUT_DIR="$2"
      shift 2
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

if [[ -z "$OUTPUT_DIR" ]]; then
  echo "Error: --output-dir is required" >&2
  exit 1
fi

# 确保输出目录是绝对路径且为空
if [[ ! "$OUTPUT_DIR" = /* ]]; then
  echo "Error: --output-dir must be an absolute path" >&2
  exit 1
fi

# 下载 OpenAPI Generator CLI (如果不存在或 SHA-256 不匹配)
download_generator() {
  mkdir -p "$TOOLS_DIR"
  local jar_path="$TOOLS_DIR/$OPENAPI_GENERATOR_JAR"
  local download_url="https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/${OPENAPI_GENERATOR_VERSION}/${OPENAPI_GENERATOR_JAR}"
  
  if [[ -f "$jar_path" ]]; then
    local actual_sha256
    actual_sha256=$(sha256sum "$jar_path" | cut -d' ' -f1)
    if [[ "$actual_sha256" == "$OPENAPI_GENERATOR_SHA256" ]]; then
      echo "OpenAPI Generator CLI already downloaded and verified"
      return 0
    else
      echo "SHA-256 mismatch, re-downloading..."
      rm -f "$jar_path"
    fi
  fi
  
  echo "Downloading OpenAPI Generator CLI ${OPENAPI_GENERATOR_VERSION}..."
  # 尝试 curl (支持代理)
  if ! curl -fsSL -o "$jar_path" "$download_url" 2>/dev/null; then
    echo "curl failed, trying wget..."
    wget -q -O "$jar_path" "$download_url"
  fi
  
  local actual_sha256
  actual_sha256=$(sha256sum "$jar_path" | cut -d' ' -f1)
  if [[ "$actual_sha256" != "$OPENAPI_GENERATOR_SHA256" ]]; then
    echo "Error: SHA-256 verification failed!" >&2
    echo "Expected: $OPENAPI_GENERATOR_SHA256" >&2
    echo "Actual:   $actual_sha256" >&2
    rm -f "$jar_path"
    exit 1
  fi
  
  echo "SHA-256 verification passed"
}

# 生成模型
generate_models() {
  local jar_path="$TOOLS_DIR/$OPENAPI_GENERATOR_JAR"
  local openapi_path="$PROJECT_ROOT/contracts/v1/generated/openapi-with-schemas.yaml"
  
  # 检查增强版 OpenAPI spec 是否存在
  if [[ ! -f "$openapi_path" ]]; then
    echo "Error: Enhanced OpenAPI spec not found: $openapi_path" >&2
    echo "Please run 'pnpm contract:generate' first to generate openapi-with-schemas.yaml" >&2
    exit 1
  fi
  
  # 确保输出目录为空
  if [[ -d "$OUTPUT_DIR" ]]; then
    rm -rf "$OUTPUT_DIR"
  fi
  mkdir -p "$OUTPUT_DIR"
  
  echo "Generating Kotlin models from $openapi_path..."
  
  # 运行 OpenAPI Generator
  java -jar "$jar_path" generate \
    -i "$openapi_path" \
    -g kotlin \
    -o "$OUTPUT_DIR" \
    --package-name "io.yggdrasil.labs.mealmate.lite.contract.generated" \
    --additional-properties=serializationLibrary=kotlinx_serialization \
    --additional-properties=generateOneOfAnyOfWrappers=true \
    --additional-properties=dateLibrary=java8 \
    --additional-properties=enumPropertyNaming=original \
    --global-property=models \
    --global-property=supportingFiles=false \
    --generate-alias-as-model
  
  echo "Generation complete"
}

# 后处理生成的文件
# 修复 OpenAPI Generator 的已知问题:
# 1. 顶层 dangling KDoc -> 移除 (ktlint 规则 standard:kdoc)
# 2. kotlin.Any? 用于 const 字段 -> 替换为 String
# 3. java.net.URI 缺少 serializer -> 替换为 String
# 4. 运行 ktlint --format 修复剩余格式问题
postprocess_models() {
  local models_dir="$OUTPUT_DIR/src/main/kotlin/io/yggdrasil/labs/mealmate/lite/contract/generated/models"
  
  if [[ ! -d "$models_dir" ]]; then
    echo "Warning: Models directory not found: $models_dir" >&2
    return
  fi
  
  echo "Post-processing generated models..."
  
  # 1. 移除顶层 dangling KDoc (OpenAPI Generator 生成的文件头注释)
  # 这些注释在 @file:Suppress 之前，违反 ktlint 的 standard:kdoc 规则
  find "$models_dir" -name "*.kt" -exec perl -i -0pe \
    's|^/\*\*\n \*\n \* Please note:.*?Do not edit this file manually\.\n \*\n \*/\n+||s' {} \;
  
  # 2. 替换 @Contextual kotlin.Any? -> String (用于 const 字段)
  # 这些字段是 JSON const，如 "op": "clear" 或 "resource": "recipe"
  find "$models_dir" -name "*.kt" -exec sed -i \
    's/@Contextual @SerialName(value = \("[^"]*"\))\n    val \([a-zA-Z]*\): kotlin\.Any?/@SerialName(value = \1)\n    val \2: kotlin.String/g' {} \;
  
  # 使用 perl 处理多行替换
  find "$models_dir" -name "*.kt" -exec perl -i -0pe \
    's/\@Contextual \@SerialName\(value = ("[^"]*")\)\s*\n\s*val ([a-zA-Z]+): kotlin\.Any\?/\@SerialName(value = \1)\n    val \2: kotlin.String/g' {} \;
  
  # 3. 替换 java.net.URI -> String (简化 URI 处理)
  find "$models_dir" -name "*.kt" -exec sed -i \
    's/java\.net\.URI/kotlin.String/g' {} \;
  
  # 4. 移除不需要的 import
  find "$models_dir" -name "*.kt" -exec sed -i \
    '/^import java\.net\.URI$/d' {} \;
  
  # 5. 使用 gradle ktlintFormat 格式化（在 sync 完成后由 gradle task 执行）
  # 注意：ktlint 格式化会在 syncContractModels task 之后由 gradle 执行
  echo "Note: Run './gradlew ktlintFormat' to format generated code"
  
  echo "Post-processing complete"
}

# 主流程
main() {
  download_generator
  generate_models
  postprocess_models
}

main
